// MODEL
//  data = {
//     info: number | null,
//     state: string,
//     id: number,
//     gps1: number | null,
//     gps2: number | null,
//     gprs1: number | null,
//     gprs2: number | null,
//     bat: number | null,
//     alim: boolean,
//     batteryHigh: boolean,
//     batteryLow: boolean,
// }


export const data = [
    {
        info: 111,
        state: "oka",
        id: 1,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 222,
        state: "oka",
        id: 22,
        gps1: 1,
        gps2: 2,
        gprs1: 2, 
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 363,
        state: "not",
        id: 33,
        gps1: 2,
        gprs1:2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        info: 444,
        id: 4,
        state: "oka",
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },



    {
        info: 111,
        state: "oka",
        id: 1,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 222,
        state: "oka",
        id: 222,
        gps1: 1,
        gps2: 2,
        gprs1: 2, 
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 363,
        state: "not",
        id: 333,
        gps1: 2,
        gprs1:2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        info: 444,
        id: 44,
        state: "oka",
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 111,
        state: "oka",
        id: 111,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 222,
        state: "oka",
        id: 202,
        gps1: 1,
        gps2: 2,
        gprs1: 2, 
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 363,
        state: "not",
        id: 3333,
        gps1: 2,
        gprs1:2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        info: 444,
        id: 444,
        state: "oka",
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 111,
        state: "oka",
        id: 101,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 222,
        state: "oka",
        id: 2202,
        gps1: 1,
        gps2: 2,
        gprs1: 2, 
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 363,
        state: "not",
        id: 3033,
        gps1: 2,
        gprs1:2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        info: 444,
        id: 404,
        state: "oka",
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 111,
        state: "oka",
        id: 110,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 222,
        state: "oka",
        id: 2212,
        gps1: 1,
        gps2: 2,
        gprs1: 2, 
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        info: 363,
        state: "not",
        id: 303033,
        gps1: 2,
        gprs1:2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        info: 444,
        id: 404044,
        state: "oka",
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
]