export const data = [
    {
        name: 1,
        state: "oka",
        id: 1,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 2,
        state: "oka",
        id: 2,
        gps1: 1,
        gps2: 2,
        gprs1: 2,
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 3,
        state: "not",
        id: 3,
        gps1: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        name: 4,
        state: "oka",
        id: 4,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 5,
        state: "oka",
        id: 5,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 6,
        state: "oka",
        id: 6,
        gps1: 1,
        gps2: 2,
        gprs1: 2,
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 7,
        state: "not",
        id: 7,
        gps1: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        name: 8,
        state: "oka",
        id: 8,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 9,
        state: "oka",
        id: 9,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 10,
        state: "oka",
        id: 10,
        gps1: 1,
        gps2: 2,
        gprs1: 2,
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 11,
        state: "not",
        id: 11,
        gps1: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        name: 12,
        state: "oka",
        id: 12,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 13,
        state: "oka",
        id: 13,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 14,
        state: "oka",
        id: 14,
        gps1: 1,
        gps2: 2,
        gprs1: 2,
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 15,
        state: "not",
        id: 15,
        gps1: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        name: 16,
        state: "oka",
        id: 16,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 17,
        state: "oka",
        id: 17,
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 2,
        bat: 99,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 18,
        state: "oka",
        id: 18,
        gps1: 1,
        gps2: 2,
        gprs1: 2,
        bat: 89,
        alim: true,
        batteryHigh: true,
        batteryLow: false,
    },
    {
        name: 19,
        state: "not",
        id: 19,
        gps1: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 23,
        alim: false,
        batteryHigh: false,
        batteryLow: true,
    },
    {
        name: 20,
        id: 20,
        state: "oka",
        gps1: 2,
        gps2: 2,
        gprs1: 2,
        gprs2: 1,
        bat: 88,
        alim: false,
        batteryHigh: true,
        batteryLow: false,
    },
];
